### ISSUE TITLE
Error messages are not explanatory

### ISSUE THREAD

**Issue by brnkhy** [mapbox/vector-tile-cs#25]
I was working with contour lines in terrain v1 dataset and it turns out that contour data is only available for higher zoom levels like z16. I tried with z14 for a long time and got "Exception: Layer has invalid version: contour" error message which I couldn't understand at all. I'm not sure if it's possible to understand what's wrong when that problem occurs but it would be nice to get those error messages to be a little more self explanatory.

cc @BergWerkGIS

**Comment by BergWerkGIS** [comment]
Done https://github.com/mapbox/vector-tile-cs/blob/5b4c01e2c0cb0ae2700349b153a3958e4083d2a7/src/VectorTileReader/VectorTileReader.cs#L172-L177
