### ISSUE TITLE
[Feature Request] Convert geojson to vector tile

### ISSUE THREAD

**Issue by donnyv** [mapbox/vector-tile-cs#42]
I think adding the ability to convert geojson to vector tiles would make it a great tool for C# developers. Right now nothing exists in the C# world to do this.

**Comment by deaquino** [comment]
@donnyv have you found anything?

**Comment by donnyv** [comment]
@deaquino Unfortunately no, your best bet is to create a NodeJS app using this https://github.com/mapbox/geojson-vt and then call it using C#. The reason I say use the geojson-vt lib is because when the spec changes, you get the updates for free. Since geojson-vt is maintained by Mapbox.

**Comment by wilhelmberg** [comment]
**EDIT -->**
Sorry , misread the question.
GeoJSON -> VT: No plans for implementation.
**<-- EDIT**

----

This project has `ToGeoJson` built-in, but:

* it is hacky and was intended just for debugging during early development only
* no plans for further development

https://github.com/mapbox/vector-tile-cs/blob/2fac36b47a778510096ac39cbc5e983337235884/src/ExtensionMethods/VectorTile.cs#L19-L39
