### ISSUE TITLE
Is Grpc.AspNetCore implementation in the roadmap?

### ISSUE THREAD

**Issue by deaquino** [mapbox/vector-tile-cs#44]
Just to know if there are any plans to adapt it to the new gRPC approach.

**Comment by wilhelmberg** [comment]
No, because this library
* has been dormant for a while.
* is hard coded to the Mapbox VT spec and works directly on the bytes of the data buffers without any additional dependencies (protobuf) for efficiency and speed and to be as lightweight as possible.
